[package]
edition = "2021"
name = "crd"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = {version = "0.4.19", features = ["serde"]}
futures = "0.3"
http = "0.2"
k8s-openapi = {version = "0.14.0", features = ["v1_22"], default-features = false}
log = "0.4.6"
schemars = {version = "0.8.8", features = ["chrono"]}
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
serde_yaml = "0.8.23"

[dependencies.kube]
features = ["runtime", "client", "derive"]
version = "0.71.0"
