[package]
edition = "2021"
name = "rcrd"
version = "0.1.0"

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[[bin]]
doc = false
name = "crdgen"
path = "src/crdgen.rs"

[lib]
name = "controller"
path = "src/lib.rs"

[dependencies]
aws-config = "0.10.1"
aws-sdk-appconfig = "0.10.1"
aws-sdk-cloudformation = "0.10.1"
aws-sdk-secretsmanager = "0.10.1"
aws-sdk-ssm = "0.10.1"
chrono = {version = "0.4.19", features = ["serde"]}
k8s-openapi = {version = "0.14.0", features = ["v1_22"], default-features = false}
schemars = {version = "0.8.8", features = ["chrono"]}
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
serde_yaml = "0.8.23"
thiserror = "1.0.30"
tokio = {version = "1.16.1", features = ["macros", "rt-multi-thread"]}

[dependencies.kube]
features = ["runtime", "client", "derive"]
version = "0.71.0"
