apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  selector:
    matchLabels:
      app: localstack
  replicas: 1
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack
          ports:
            - containerPort: 4566
              name: localstack
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  # selector tells Kubernetes what Deployment this Service
  # belongs to
  selector:
    app: localstack
  ports:
    - port: 80
      targetPort: localstack
