[package]
edition = "2021"
name = "remote-secrets"
version = "0.1.0"

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[lib]
name = "controller"
path = "src/lib.rs"

[dependencies]
actix-web = "4.0.1"
anyhow = "1.0"
aws-config = "0.10.1"
aws-sdk-appconfig = "0.10.1"
aws-sdk-cloudformation = "0.10.1"
aws-sdk-secretsmanager = "0.10.1"
aws-sdk-ssm = "0.10.1"
aws-smithy-http = "0.40.2"
aws-types = "0.10.1"
cached = "0.34.0"
chrono = {version = "0.4.19", features = ["serde"]}
crd = {path = "../crd"}
futures = "0.3"
http = "0.2"
json_dotpath = "1.1.0"
k8s = {path = "../k8s"}
k8s-openapi = {version = "0.14.0", features = ["v1_22"], default-features = false}
log = "0.4.6"
log4rs = "1.1.1"
plugins = {path = "../plugins"}
prometheus = "0.13.0"
reqwest = {version = "0.11", features = ["json"]}
schemars = {version = "0.8.8", features = ["chrono"]}
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
serde_yaml = "0.8.23"
tokio = {version = "1.16.1", features = ["macros", "rt-multi-thread"]}
utils = {path = "../utils"}

[dev-dependencies]
httpmock = "0.6.5"
k9 = "0.11.1"

[dependencies.kube]
features = ["runtime", "client", "derive"]
version = "0.71.0"
