apiVersion: jerry153fish.com/v1beta1
kind: RSecret # Identifier of the resource type.
metadata:
  name: test-rsecret # Name of the "RSecret" custom resource instance, may be changed to your liking
  namespace: default # Namespace must exist and account in KUBECONFIG must have sufficient permissions
spec:
  description: "test rsecret" # Optional description of the resource
  resources:
    - backend: SSM
      data:
        - value: MyStringParameter
          key: test-rsecret-ssm-param
    - backend: SSM
      data:
        - value: MyJsonParameter
    - backend: Plaintext
      data:
        - value: test-rsecret-plaintext-value
          key: test-rsecret-plaintext
        - value: test-rsecret-plaintext-value-1
          key: test-rsecret-plaintext-1
    - backend: SecretManager
      data:
        - value: MyTestSecret
          key: test-rsecret-secretmanager
    - backend: SecretManager
      data:
        - value: MyJsonSecret
    - backend: Cloudformation
      data:
        - value: MyTestStack
        - value: MyTestStack
          key: test-cfn-stack
          remote_path: S3Bucket
    - backend: Vault
      data:
        - value: vaultString
          key: vault-string
        - value: vaultJson
